### ISSUE TITLE
No Screenshots

### ISSUE THREAD

**Issue by agwilt** [Gnurfos/MksExplainer#1]
As a mod consumer, I think this looks interesting but I don't really know what to expect if I install it ...

**Comment by Gnurfos** [comment]
There is one on the "release thread" in the KSP forums.
Do you mean you'd like one on SpaceDock too, or here in the source repo ?

**Comment by agwilt** [comment]
Ah, I found the mod through SpaceDock. I'd add a picture in SpaceDock, or at least link to the forum thread. To be honest, I didn't know the thread existed 😛

**Comment by Gnurfos** [comment]
I just added links to the forum and to a screenshot on both SpaceDock and here.
